<?php 
 /** @file
 * Drupal Module: Google Tag Manager
 * Provides integration with Google Tag Manager.
 * @Author: <a href="http://tinyurl.com/c6tgju5">+Rainer Maurer</a>
 */


 /**
* Hook_perm implementation
 */
function gtm_perm() {
  return array('administer google tag manager');
}

 /**
 * Hook_menu() implementation
 */
function gtm_menu() {

  $items['admin/settings/gtm'] = array(
    'title' => 'Google Tag Manager',
    'description' => 'Configure the settings for Google Tag Manager.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gtm_admin_settings_form'),
    'access arguments' => array('administer google tag manager'),
    'file' => 'gtm.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function gtm_footer($main = 0) {
  global $user;

 // Check if we should track the currently active user's role
    $track = 0;
    if (is_array($user->roles)) {
    foreach ($user->roles as $role) {
      $role = str_replace(' ', '_', $role);
      $track += variable_get("gtm_track_{$role}", FALSE);
    }
  }
 // Don't track page views in the admin sections, or for certain roles
    if (arg(0) != 'admin' && $track > 0) {
    $snippet = variable_get('gtm', '');
      if (!empty($snippet)) {
      return $snippet;
    }
    else {
    return '';
    }
  }

}
